### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by pat-s** [r-hub/rversions#25]
``` r
rversions::r_versions()
#> Error in curl_fetch_memory(r_svn_url(), handle = h): SSL certificate problem: certificate has expired
```

<sup>Created on 2020-05-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gaborcsardi** [comment]
The svn.r-project.org certificate is valid *now*. Maybe you are behind some proxy? Anyway, it is not our certificate.

**Comment by pat-s** [comment]
No proxy.

FWIW I see similar errors on GHA for codecov runs lately.

**Comment by gaborcsardi** [comment]
Can you please tell your OS and libcurl version? Also show a link to GHA? Thanks.

**Comment by pat-s** [comment]
macOS 10.15.5

```
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```


Can't find a GHA example right now, too many repos. Will report back here the next time I come across one.

**Comment by pat-s** [comment]
here is one: https://github.com/mlr3learners/mlr3learners.kernlab/runs/723393341?check_suite_focus=true#step:17:41

**Comment by gaborcsardi** [comment]
OK, emailed R-devel about this:
https://www.mail-archive.com/r-devel@r-project.org/msg42260.html

**Comment by gaborcsardi** [comment]
Seems like this was fixed on the r-project.org website. I am not entirely sure why the GHA run was failing and which web site covr was trying to access, apart from codecov.io. codecov.io seems to be fine, so hopefully those issues are gone as well.

**Comment by gaborcsardi** [comment]
@pat-s Btw. can you pls let me know if you see this again on GHA. If it happens again, then we can report it.

**Comment by pat-s** [comment]
Sure. Thanks Gabor!
