### ISSUE TITLE
Latest R version 4.0.3 seems not stable and giving unnecessary errors. 

### ISSUE THREAD

**Issue by arubhardwaj** [r-hub/rversions#27]
I just updated my R base yesterday and stated working on `plm` package. When I was running the `random` effects model in R, I found an unexpected error that number of variables are more than estimable. The exact error was:

`Error in swar_Between_check(estm[[2]], method) :    model not estimable as there are 8 coefficient(s) (incl. intercept) to be estimated for the between model but only 6 individual(s)
 `

For the time being, i ignored that assuming that it must be an issue with `plm` package. But, later, I asked someone else to update R to `4.0.3` version and was told that this error is occurring there too, which was working fine earlier in older version. 

I confirmed that this error is not because of `plm` package when `lm()` also gave same type of error: of more variables than estimable.

I was running only 6 variables. Although, it should not matter since there is no limit on number of variables in calculating models through these functions.

**Comment by gaborcsardi** [comment]
Hi, this repository is for the rversions R package: https://cran.rstudio.com/web/packages/rversions/

For generic R questions see the R-help mailing list, and if you have a problem with an R package, contact its maintainer.
