### ISSUE TITLE
Out of sync with R for Windows's notion of "R-release"

### ISSUE THREAD

**Issue by krlmlr** [r-hub/rversions#4]
https://cran.r-project.org/bin/windows/base/ -> R 3.3.0
http://rversions.r-pkg.org/r-release -> R 3.2.5

Any idea?

Fixes krlmlr/r-appveyor#64.

**Comment by gaborcsardi** [comment]
I update this manually, because I need an R build for metacran/r-builder
before updating it.

Just updated it.

I'll add a separate r-builder-release and r-release will always point to
the latest release to avoid these problems in the future.

I am sorry for the trouble!

**Comment by gaborcsardi** [comment]
Btw. this belongs to https://github.com/metacran/rversions.app

**Comment by krlmlr** [comment]
The good old chicken-and-egg problem ;-) Thanks for the quick fix.

I don't know much about the R release process, but perhaps it helps to have r-release-win, r-release-osx, ... that update whenever new bits become available.

**Comment by gaborcsardi** [comment]
That's a good idea! We can have 
- `r-release` — tag in SVN, this is what we have currently
- `r-release-tarball` — source tarball available for download
- `r-release-win` — windows installer available for download
- `r-release-osx` — OS X installer available for download
- `r-release-rbuilder` metacran/r-builder build of last R version
