### ISSUE TITLE
Return version nicknames?

### ISSUE THREAD

**Issue by maelle** [r-hub/rversions#8]
Could this package also return version nicknames, either optionally in `r_versions()` or in a new function?

From R 2.15.1 there seems to be a special file with the info e.g. https://svn.r-project.org/R/tags/R-2-15-1/VERSION-NICK (but it's not always present :thinking: )

**Comment by gaborcsardi** [comment]
Yeah, we could have these. Seems like it is always there from 2.15.0. It is quite some number of requests to make, though.

**Comment by maelle** [comment]
it'd be such a cool feature :grin: should it be a separate function because of the number of requests?

**Comment by gaborcsardi** [comment]
or we perform all queries in parallel

**Comment by maelle** [comment]
is it nice for the SVN repo?

**Comment by gaborcsardi** [comment]
We could also cache them somewhere on the disk, and query unknown ones. And limit the number of parallel requests to 5-10.

**Comment by maelle** [comment]
somewhere on the disk like what `rhub` does for the csv with emails and tokens?

**Comment by gaborcsardi** [comment]
yeah

**Comment by gaborcsardi** [comment]
or we could query the web service as well.

**Comment by maelle** [comment]
actually the info on versions < 3.5 is unlikely to change at all so why wouldn't it be shipped with the package for such versions?

**Comment by gaborcsardi** [comment]
yeah, good idea

**Comment by maelle** [comment]
and in inst/ somewhere there'd be the code creating the data.frame one'd ship with the package so it's easier to update it before each release. the function `rversions()` would thus just need to add info between the latest version in that data.frame and `r_release()`.
